- name: install apache2 package (Ubuntu)
  tags: apache,apache2,ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"


- name: copy html file for site
  tags: apache,apache,apache2,httpd
  copy:
    src: /home/gowri/roles/web_servers/template/index.html.j2
    dest: /var/www/html/index.html
 # when: env == 'staging'

- name: Start and enable Apache
  service:
    name: apache2
    state: started
    enabled: yes
  tags: apache
